name: CI


on:
  push:
    branches:
      - master
  repository_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest .
    
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest

  test:
    runs-on: ubuntu-latest
    environment: Test
    env:
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: alice
          POSTGRES_PASSWORD: bob
          POSTGRES_DB: project_test_db
        options: >-
          --health-cmd="pg_isready -U alice"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      TEST_DATABASE_URL: postgresql://alice:bob@localhost:5432/project_test_db

    needs: build-image
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest

      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest \
          python3 -m unittest discover -s tests
      
      - name: Dummy step to ensure the job runs
        run: echo "Tests completed successfully"
