name: CI


on:
  push:
    branches:
      - master


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest .
    
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest

  test:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest

      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/project-management-api:latest \
          python3 -m unittest discover -s tests
      
      - name: Dummy step to ensure the job runs
        run: echo "Tests completed successfully"
